source('code/common.R')
library(ggplot2);library(patchwork)

ranking<-validate_table(read.csv('data/ranking.csv',check.names=FALSE,fileEncoding='UTF-8'),c('gene_id','rank','statistic'),'ranking')
hits<-validate_table(read.csv('data/hits.csv',check.names=FALSE,fileEncoding='UTF-8'),c('pathway_id','gene_id','rank'),'hits')
enrichment<-validate_table(read.csv('data/enrichment.csv',check.names=FALSE,fileEncoding='UTF-8'),c('pathway_id','description','set_size','enrichment_score','nes','p_adjust'),'enrichment')
require_numeric(ranking,c('rank','statistic'));require_numeric(hits,'rank');require_numeric(enrichment,c('set_size','enrichment_score','nes','p_adjust'))
valid_labels<-function(v)all(!is.na(v)&nzchar(trimws(as.character(v))))
if(!valid_labels(ranking$gene_id)||anyDuplicated(ranking$gene_id)||!identical(as.numeric(ranking$rank),as.numeric(seq_len(nrow(ranking))))||any(diff(ranking$statistic)>0))stop('ranking must have unique genes, contiguous ranks and descending statistics')
if(!valid_labels(enrichment$pathway_id)||!valid_labels(enrichment$description)||anyDuplicated(enrichment$pathway_id))stop('enrichment identifiers must be unique and labels present')
if(any(enrichment$set_size<=0|enrichment$set_size!=floor(enrichment$set_size))||any(enrichment$p_adjust<0|enrichment$p_adjust>1)||any(abs(enrichment$enrichment_score)>1)||any(sign(enrichment$enrichment_score)!=sign(enrichment$nes)))stop('invalid stored enrichment ranges or ES/NES direction')
if(!valid_labels(hits$gene_id)||!valid_labels(hits$pathway_id)||anyDuplicated(hits[c('pathway_id','rank')])||any(hits$rank<1|hits$rank>nrow(ranking)|hits$rank!=floor(hits$rank))||!setequal(hits$pathway_id,enrichment$pathway_id))stop('hit ranks and pathway keys do not match ranking/enrichment')
if(any(as.character(hits$gene_id)!=as.character(ranking$gene_id[hits$rank])))stop('hit gene identifiers do not match supplied ranking positions')
hit_counts<-table(factor(hits$pathway_id,levels=enrichment$pathway_id));if(any(as.numeric(hit_counts)!=enrichment$set_size))stop('hit count does not match supplied set_size')
if(!is.numeric(params$font_size)||params$font_size<=0||!is.numeric(params$width)||params$width<=0||!is.numeric(params$height)||params$height<=0||!is.numeric(params$dpi)||params$dpi<72)stop('invalid rendering dimensions or font size')

curves<-validate_table(read.csv('data/curves.csv',check.names=FALSE,fileEncoding='UTF-8'),c('pathway_id','rank','running_es'),'curves')
require_numeric(curves,c('rank','running_es'))
if(!setequal(curves$pathway_id,enrichment$pathway_id)||anyDuplicated(curves[c('pathway_id','rank')]))stop('curve pathway/rank keys must match enrichment')
peaks<-list()
for(i in seq_len(nrow(enrichment))){
 id<-enrichment$pathway_id[i];d<-curves[curves$pathway_id==id,,drop=FALSE];d<-d[order(d$rank),]
 if(!identical(as.numeric(d$rank),as.numeric(ranking$rank)))stop('curve ranks must exactly match complete ranking for every pathway')
 v<-d$running_es;if(any(abs(v)>1)||abs(tail(v,1))>1e-6)stop('running ES must be bounded and return to zero')
 j<-which.max(abs(v));if(abs(v[j]-enrichment$enrichment_score[i])>1e-6)stop('curve extreme does not match supplied enrichment_score')
 peaks[[i]]<-data.frame(pathway_id=id,rank=d$rank[j],running_es=v[j])
}
cols<-setNames(c(params$positive_colour,params$negative_colour)[ifelse(enrichment$nes>=0,1,2)],enrichment$pathway_id)
labels<-setNames(vapply(enrichment$description,function(x)paste(strwrap(x,width=65),collapse='\n'),character(1)),enrichment$pathway_id)
lev<-enrichment$pathway_id;curves$pathway_id<-factor(curves$pathway_id,levels=lev);hits$pathway_id<-factor(hits$pathway_id,levels=lev);peaks<-do.call(rbind,peaks);peaks$pathway_id<-factor(peaks$pathway_id,levels=lev)
ann<-enrichment;ann$pathway_id<-factor(ann$pathway_id,levels=lev);ann$text<-sprintf('ES = %.3f   NES = %.3f   adjusted P = %.2e',ann$enrichment_score,ann$nes,ann$p_adjust)
facet<-facet_wrap(~pathway_id,ncol=1,labeller=as_labeller(labels))
xscale<-scale_x_continuous(limits=c(1,nrow(ranking)),expand=c(0,0))
p1<-ggplot(curves,aes(rank,running_es,colour=pathway_id))+geom_hline(yintercept=0,colour='grey65',linewidth=.3)+geom_line(linewidth=.65)+geom_point(data=peaks,size=2)+geom_text(data=ann,aes(x=Inf,y=Inf,label=text),inherit.aes=FALSE,hjust=1.05,vjust=1.2,size=params$font_size/3.8)+scale_colour_manual(values=cols,guide='none')+xscale+facet+labs(x=NULL,y='Running enrichment score')+plot_theme()+theme(axis.text.x=element_blank(),axis.ticks.x=element_blank(),strip.background=element_rect(fill='#F2F2F2',colour=NA),strip.text=element_text(face='bold'),panel.spacing=grid::unit(1,'lines'))
p2<-ggplot(hits,aes(x=rank,xend=rank,y=0,yend=1,colour=pathway_id))+geom_segment(linewidth=.25)+scale_colour_manual(values=cols,guide='none')+xscale+facet+labs(x=NULL,y='Gene-set hits')+plot_theme()+theme(axis.text=element_blank(),axis.ticks=element_blank(),strip.text=element_blank(),strip.background=element_blank(),panel.spacing=grid::unit(.3,'lines'))
p3<-ggplot(ranking,aes(rank,statistic))+geom_area(fill='#A8ADB2')+geom_hline(yintercept=0,linewidth=.3)+xscale+labs(x='Gene rank: descending supplied statistic (high → low)',y='Ranked statistic')+plot_theme()
p<-p1/p2/p3+plot_layout(heights=c(4.5,1.5,1.4))+plot_annotation(title=params$title,caption='Derived teaching example; supplied NES and adjusted P retained; no enrichment or permutation rerun')
save_gg(p);writeLines(capture.output(sessionInfo()),'sessionInfo.txt')
write.csv(peaks,'evidence/curve-extrema.csv',row.names=FALSE)
cat('OK: supplied running ES curves and ranked statistics rendered\n')
