source('code/common.R')
library(ggplot2);library(patchwork)
d<-validate_table(read.csv('data/enrichment.csv',check.names=FALSE,fileEncoding='UTF-8'),c('pathway_id','description','group','celltype','qvalue','up_count','down_count','all_count','de_score'),'DEscore')
require_numeric(d,c('qvalue','up_count','down_count','all_count','de_score'))
if(anyNA(d[c('pathway_id','description','group','celltype')])||any(!nzchar(trimws(as.character(unlist(d[c('pathway_id','description','group','celltype')]))))))stop('DEscore labels must be present')
if(anyDuplicated(d[c('pathway_id','group','celltype')]))stop('duplicate pathway/group/celltype keys')
if(any(d$qvalue<0|d$qvalue>1)||any(d$up_count<0|d$down_count<0|d$all_count<=0)||any(d$up_count!=floor(d$up_count)|d$down_count!=floor(d$down_count)|d$all_count!=floor(d$all_count)))stop('invalid qvalue or integer gene counts')
if(any(d$up_count+d$down_count!=d$all_count)||any(abs(d$de_score-(d$up_count-d$down_count)/d$all_count)>1e-6))stop('DEscore denominator or supplied signed score is inconsistent')
if(!is.numeric(params$q_display_floor)||length(params$q_display_floor)!=1||!is.finite(params$q_display_floor)||params$q_display_floor<=0||params$q_display_floor>1)stop('q_display_floor must be within (0,1]')
if(!is.numeric(params$pathway_wrap)||params$pathway_wrap<10||!is.numeric(params$max_bubble_size)||params$max_bubble_size<=0||params$width<=0||params$height<=0||params$dpi<72||params$font_size<=0)stop('invalid rendering parameter')
d$y<-seq_len(nrow(d));d$display_score<--log10(pmax(d$qvalue,params$q_display_floor));groups<-unique(d$group)
if(length(groups)>length(params$group_colours))stop('group_colours must cover all input groups')
cols<-setNames(unlist(params$group_colours)[seq_along(groups)],groups)
labels<-vapply(d$description,function(x)paste(strwrap(x,width=params$pathway_wrap),collapse='\n'),character(1));ylim<-c(.4,nrow(d)+.6)
blocks<-do.call(rbind,lapply(split(d,d$group),function(x)data.frame(group=x$group[1],y=(min(x$y)+max(x$y))/2,ymin=min(x$y)-.49,ymax=max(x$y)+.49)))
# 同一组可以有分离行，条带按每行画；组名只在连续块的中心标注。
runs<-rle(d$group);end<-cumsum(runs$lengths);start<-end-runs$lengths+1;blocks<-data.frame(group=runs$values,y=(start+end)/2)
p1<-ggplot(d,aes(y=y))+geom_tile(aes(x=1,fill=group),width=.7,height=.98)+geom_text(data=blocks,aes(x=1,y=y,label=group),angle=90,fontface='bold.italic',size=params$font_size/3.3)+scale_fill_manual(values=cols,guide='none')+scale_y_continuous(breaks=d$y,labels=labels,limits=ylim,expand=c(0,0))+scale_x_continuous(limits=c(.5,1.5),expand=c(0,0))+theme_void(base_size=params$font_size,base_family=params$font_family)+theme(axis.text.y=element_text(colour='black',size=params$font_size),plot.margin=margin(5,0,5,5))
p2<-ggplot(d,aes(y=y))+geom_segment(aes(x=0,xend=display_score,yend=y,colour=group),linewidth=.7,show.legend=FALSE)+scale_colour_manual(values=cols)+geom_point(aes(x=display_score,size=all_count,fill=de_score),shape=21,colour='grey45',stroke=.25)+scale_fill_gradient2(low='#810F7C',mid='#F7FCFD',high='#023858',midpoint=0,limits=c(-1,1),name='DEscore')+scale_size_area(max_size=params$max_bubble_size,name='Up + down genes')+scale_y_continuous(limits=ylim,expand=c(0,0))+scale_x_continuous(expand=expansion(mult=c(0,.12)))+labs(x='-log10(provided q value)',y=NULL)+plot_theme()+theme(axis.text.y=element_blank(),axis.ticks.y=element_blank(),axis.line.y=element_blank(),plot.margin=margin(5,5,5,0))
p<-p1+p2+plot_layout(widths=c(.35,5))+plot_annotation(title=params$title,caption='Teaching-example precomputed enrichment; DEscore = (up_count − down_count) / (up_count + down_count). No enrichment test rerun.')
save_gg(p);writeLines(capture.output(sessionInfo()),'sessionInfo.txt')
write.csv(d[c('pathway_id','group','celltype','up_count','down_count','all_count','de_score','qvalue','display_score','y')],'evidence/display-values.csv',row.names=FALSE)
cat('OK: supplied DEscore and q values rendered\n')
